import {FormEvent, FormEventHandler, useState} from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function registration() {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [repeat, setRepeat] = useState('');
    const [gender, setGender] = useState('');
    const [accept, setAccept] = useState(false);

    const handleSubmit = (e:FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const data = {
            username,
            password,
            accept,
        };
        console.log(data);
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <form onSubmit={handleSubmit} className={styles.form}>
                    <label htmlFor="name"></label>
                    <input
                        id="name"
                        type="text"
                        placeholder='username'
                        onChange={e => setUsername(e.target.value)}
                    />
                    <input
                        id="passw"
                        type="password"
                        placeholder='password'
                        onChange={e => setPassword(e.target.value)}
                    />
                    <input
                        id="rep"
                        type="password"
                        placeholder='repeat pass'
                        onChange={e => setRepeat(e.target.value)}
                    />
                    <input
                        id="gender"
                        type="text"
                        placeholder='gender'
                        onChange={e => setGender(e.target.value)}
                    />
                    <h1>You are accept our policy?</h1>
                    <input
                        id="accept"
                        type="checkbox"
                        onChange={e => setAccept(true)}
                    />

                    <button type="submit">Registration</button>
                </form>
            </main>
        </div>
    );
}